/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteRouteImport } from './routes/_panel/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char126IndexRouteImport } from './routes/~/index'
import { Route as RpcIndexRouteImport } from './routes/rpc/index'
import { Route as RpcSplatRouteImport } from './routes/rpc/$'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as PanelIntegracaoRouteImport } from './routes/_panel/integracao'
import { Route as PanelOrganizacaoHashRouteRouteImport } from './routes/_panel/$organizacaoHash/route'
import { Route as PanelOrganizacaoHashIndexRouteImport } from './routes/_panel/$organizacaoHash/index'
import { Route as Char126AcessoTokenRouteImport } from './routes/~/acesso/$token'
import { Route as PanelOrganizacaoHashRelatoriosRouteImport } from './routes/_panel/$organizacaoHash/relatorios'
import { Route as PanelOrganizacaoHashIntegracaoRouteImport } from './routes/_panel/$organizacaoHash/integracao'
import { Route as PanelOrganizacaoHashInstanciasRouteImport } from './routes/_panel/$organizacaoHash/instancias'
import { Route as PanelOrganizacaoHashEquipeRouteImport } from './routes/_panel/$organizacaoHash/equipe'
import { Route as PanelOrganizacaoHashContatosRouteImport } from './routes/_panel/$organizacaoHash/contatos'
import { Route as PanelOrganizacaoHashAjustesRouteRouteImport } from './routes/_panel/$organizacaoHash/ajustes/route'
import { Route as PanelOrganizacaoHashInboxIndexRouteImport } from './routes/_panel/$organizacaoHash/inbox/index'
import { Route as PanelOrganizacaoHashAjustesIndexRouteImport } from './routes/_panel/$organizacaoHash/ajustes/index'
import { Route as Char126EmailEmailHashBloqueadoRouteImport } from './routes/~/email/$emailHash/bloqueado'
import { Route as PanelOrganizacaoHashAjustesUsuariosRouteImport } from './routes/_panel/$organizacaoHash/ajustes/usuarios'
import { Route as PanelOrganizacaoHashAjustesEtiquetasRouteImport } from './routes/_panel/$organizacaoHash/ajustes/etiquetas'
import { Route as PanelOrganizacaoHashAjustesConexaoRouteImport } from './routes/_panel/$organizacaoHash/ajustes/conexao'
import { Route as PanelOrganizacaoHashInboxInstanceIdIndexRouteImport } from './routes/_panel/$organizacaoHash/inbox/$instanceId/index'
import { Route as PanelOrganizacaoHashInboxInstanceIdRelatoriosIndexRouteImport } from './routes/_panel/$organizacaoHash/inbox/$instanceId/relatorios/index'

const PanelRouteRoute = PanelRouteRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char126IndexRoute = Char126IndexRouteImport.update({
  id: '/~/',
  path: '/~/',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcIndexRoute = RpcIndexRouteImport.update({
  id: '/rpc/',
  path: '/rpc/',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIntegracaoRoute = PanelIntegracaoRouteImport.update({
  id: '/integracao',
  path: '/integracao',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelOrganizacaoHashRouteRoute =
  PanelOrganizacaoHashRouteRouteImport.update({
    id: '/$organizacaoHash',
    path: '/$organizacaoHash',
    getParentRoute: () => PanelRouteRoute,
  } as any)
const PanelOrganizacaoHashIndexRoute =
  PanelOrganizacaoHashIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)
const Char126AcessoTokenRoute = Char126AcessoTokenRouteImport.update({
  id: '/~/acesso/$token',
  path: '/~/acesso/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelOrganizacaoHashRelatoriosRoute =
  PanelOrganizacaoHashRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)
const PanelOrganizacaoHashIntegracaoRoute =
  PanelOrganizacaoHashIntegracaoRouteImport.update({
    id: '/integracao',
    path: '/integracao',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)
const PanelOrganizacaoHashInstanciasRoute =
  PanelOrganizacaoHashInstanciasRouteImport.update({
    id: '/instancias',
    path: '/instancias',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)
const PanelOrganizacaoHashEquipeRoute =
  PanelOrganizacaoHashEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)
const PanelOrganizacaoHashContatosRoute =
  PanelOrganizacaoHashContatosRouteImport.update({
    id: '/contatos',
    path: '/contatos',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)
const PanelOrganizacaoHashAjustesRouteRoute =
  PanelOrganizacaoHashAjustesRouteRouteImport.update({
    id: '/ajustes',
    path: '/ajustes',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)
const PanelOrganizacaoHashInboxIndexRoute =
  PanelOrganizacaoHashInboxIndexRouteImport.update({
    id: '/inbox/',
    path: '/inbox/',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)
const PanelOrganizacaoHashAjustesIndexRoute =
  PanelOrganizacaoHashAjustesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PanelOrganizacaoHashAjustesRouteRoute,
  } as any)
const Char126EmailEmailHashBloqueadoRoute =
  Char126EmailEmailHashBloqueadoRouteImport.update({
    id: '/~/email/$emailHash/bloqueado',
    path: '/~/email/$emailHash/bloqueado',
    getParentRoute: () => rootRouteImport,
  } as any)
const PanelOrganizacaoHashAjustesUsuariosRoute =
  PanelOrganizacaoHashAjustesUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => PanelOrganizacaoHashAjustesRouteRoute,
  } as any)
const PanelOrganizacaoHashAjustesEtiquetasRoute =
  PanelOrganizacaoHashAjustesEtiquetasRouteImport.update({
    id: '/etiquetas',
    path: '/etiquetas',
    getParentRoute: () => PanelOrganizacaoHashAjustesRouteRoute,
  } as any)
const PanelOrganizacaoHashAjustesConexaoRoute =
  PanelOrganizacaoHashAjustesConexaoRouteImport.update({
    id: '/conexao',
    path: '/conexao',
    getParentRoute: () => PanelOrganizacaoHashAjustesRouteRoute,
  } as any)
const PanelOrganizacaoHashInboxInstanceIdIndexRoute =
  PanelOrganizacaoHashInboxInstanceIdIndexRouteImport.update({
    id: '/inbox/$instanceId/',
    path: '/inbox/$instanceId/',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)
const PanelOrganizacaoHashInboxInstanceIdRelatoriosIndexRoute =
  PanelOrganizacaoHashInboxInstanceIdRelatoriosIndexRouteImport.update({
    id: '/inbox/$instanceId/relatorios/',
    path: '/inbox/$instanceId/relatorios/',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$organizacaoHash': typeof PanelOrganizacaoHashRouteRouteWithChildren
  '/integracao': typeof PanelIntegracaoRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/rpc/$': typeof RpcSplatRoute
  '/rpc/': typeof RpcIndexRoute
  '/~/': typeof Char126IndexRoute
  '/$organizacaoHash/ajustes': typeof PanelOrganizacaoHashAjustesRouteRouteWithChildren
  '/$organizacaoHash/contatos': typeof PanelOrganizacaoHashContatosRoute
  '/$organizacaoHash/equipe': typeof PanelOrganizacaoHashEquipeRoute
  '/$organizacaoHash/instancias': typeof PanelOrganizacaoHashInstanciasRoute
  '/$organizacaoHash/integracao': typeof PanelOrganizacaoHashIntegracaoRoute
  '/$organizacaoHash/relatorios': typeof PanelOrganizacaoHashRelatoriosRoute
  '/~/acesso/$token': typeof Char126AcessoTokenRoute
  '/$organizacaoHash/': typeof PanelOrganizacaoHashIndexRoute
  '/$organizacaoHash/ajustes/conexao': typeof PanelOrganizacaoHashAjustesConexaoRoute
  '/$organizacaoHash/ajustes/etiquetas': typeof PanelOrganizacaoHashAjustesEtiquetasRoute
  '/$organizacaoHash/ajustes/usuarios': typeof PanelOrganizacaoHashAjustesUsuariosRoute
  '/~/email/$emailHash/bloqueado': typeof Char126EmailEmailHashBloqueadoRoute
  '/$organizacaoHash/ajustes/': typeof PanelOrganizacaoHashAjustesIndexRoute
  '/$organizacaoHash/inbox/': typeof PanelOrganizacaoHashInboxIndexRoute
  '/$organizacaoHash/inbox/$instanceId/': typeof PanelOrganizacaoHashInboxInstanceIdIndexRoute
  '/$organizacaoHash/inbox/$instanceId/relatorios/': typeof PanelOrganizacaoHashInboxInstanceIdRelatoriosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integracao': typeof PanelIntegracaoRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/rpc/$': typeof RpcSplatRoute
  '/rpc': typeof RpcIndexRoute
  '/~': typeof Char126IndexRoute
  '/$organizacaoHash/contatos': typeof PanelOrganizacaoHashContatosRoute
  '/$organizacaoHash/equipe': typeof PanelOrganizacaoHashEquipeRoute
  '/$organizacaoHash/instancias': typeof PanelOrganizacaoHashInstanciasRoute
  '/$organizacaoHash/integracao': typeof PanelOrganizacaoHashIntegracaoRoute
  '/$organizacaoHash/relatorios': typeof PanelOrganizacaoHashRelatoriosRoute
  '/~/acesso/$token': typeof Char126AcessoTokenRoute
  '/$organizacaoHash': typeof PanelOrganizacaoHashIndexRoute
  '/$organizacaoHash/ajustes/conexao': typeof PanelOrganizacaoHashAjustesConexaoRoute
  '/$organizacaoHash/ajustes/etiquetas': typeof PanelOrganizacaoHashAjustesEtiquetasRoute
  '/$organizacaoHash/ajustes/usuarios': typeof PanelOrganizacaoHashAjustesUsuariosRoute
  '/~/email/$emailHash/bloqueado': typeof Char126EmailEmailHashBloqueadoRoute
  '/$organizacaoHash/ajustes': typeof PanelOrganizacaoHashAjustesIndexRoute
  '/$organizacaoHash/inbox': typeof PanelOrganizacaoHashInboxIndexRoute
  '/$organizacaoHash/inbox/$instanceId': typeof PanelOrganizacaoHashInboxInstanceIdIndexRoute
  '/$organizacaoHash/inbox/$instanceId/relatorios': typeof PanelOrganizacaoHashInboxInstanceIdRelatoriosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_panel': typeof PanelRouteRouteWithChildren
  '/_panel/$organizacaoHash': typeof PanelOrganizacaoHashRouteRouteWithChildren
  '/_panel/integracao': typeof PanelIntegracaoRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/rpc/$': typeof RpcSplatRoute
  '/rpc/': typeof RpcIndexRoute
  '/~/': typeof Char126IndexRoute
  '/_panel/$organizacaoHash/ajustes': typeof PanelOrganizacaoHashAjustesRouteRouteWithChildren
  '/_panel/$organizacaoHash/contatos': typeof PanelOrganizacaoHashContatosRoute
  '/_panel/$organizacaoHash/equipe': typeof PanelOrganizacaoHashEquipeRoute
  '/_panel/$organizacaoHash/instancias': typeof PanelOrganizacaoHashInstanciasRoute
  '/_panel/$organizacaoHash/integracao': typeof PanelOrganizacaoHashIntegracaoRoute
  '/_panel/$organizacaoHash/relatorios': typeof PanelOrganizacaoHashRelatoriosRoute
  '/~/acesso/$token': typeof Char126AcessoTokenRoute
  '/_panel/$organizacaoHash/': typeof PanelOrganizacaoHashIndexRoute
  '/_panel/$organizacaoHash/ajustes/conexao': typeof PanelOrganizacaoHashAjustesConexaoRoute
  '/_panel/$organizacaoHash/ajustes/etiquetas': typeof PanelOrganizacaoHashAjustesEtiquetasRoute
  '/_panel/$organizacaoHash/ajustes/usuarios': typeof PanelOrganizacaoHashAjustesUsuariosRoute
  '/~/email/$emailHash/bloqueado': typeof Char126EmailEmailHashBloqueadoRoute
  '/_panel/$organizacaoHash/ajustes/': typeof PanelOrganizacaoHashAjustesIndexRoute
  '/_panel/$organizacaoHash/inbox/': typeof PanelOrganizacaoHashInboxIndexRoute
  '/_panel/$organizacaoHash/inbox/$instanceId/': typeof PanelOrganizacaoHashInboxInstanceIdIndexRoute
  '/_panel/$organizacaoHash/inbox/$instanceId/relatorios/': typeof PanelOrganizacaoHashInboxInstanceIdRelatoriosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$organizacaoHash'
    | '/integracao'
    | '/convite/$token'
    | '/rpc/$'
    | '/rpc/'
    | '/~/'
    | '/$organizacaoHash/ajustes'
    | '/$organizacaoHash/contatos'
    | '/$organizacaoHash/equipe'
    | '/$organizacaoHash/instancias'
    | '/$organizacaoHash/integracao'
    | '/$organizacaoHash/relatorios'
    | '/~/acesso/$token'
    | '/$organizacaoHash/'
    | '/$organizacaoHash/ajustes/conexao'
    | '/$organizacaoHash/ajustes/etiquetas'
    | '/$organizacaoHash/ajustes/usuarios'
    | '/~/email/$emailHash/bloqueado'
    | '/$organizacaoHash/ajustes/'
    | '/$organizacaoHash/inbox/'
    | '/$organizacaoHash/inbox/$instanceId/'
    | '/$organizacaoHash/inbox/$instanceId/relatorios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/integracao'
    | '/convite/$token'
    | '/rpc/$'
    | '/rpc'
    | '/~'
    | '/$organizacaoHash/contatos'
    | '/$organizacaoHash/equipe'
    | '/$organizacaoHash/instancias'
    | '/$organizacaoHash/integracao'
    | '/$organizacaoHash/relatorios'
    | '/~/acesso/$token'
    | '/$organizacaoHash'
    | '/$organizacaoHash/ajustes/conexao'
    | '/$organizacaoHash/ajustes/etiquetas'
    | '/$organizacaoHash/ajustes/usuarios'
    | '/~/email/$emailHash/bloqueado'
    | '/$organizacaoHash/ajustes'
    | '/$organizacaoHash/inbox'
    | '/$organizacaoHash/inbox/$instanceId'
    | '/$organizacaoHash/inbox/$instanceId/relatorios'
  id:
    | '__root__'
    | '/'
    | '/_panel'
    | '/_panel/$organizacaoHash'
    | '/_panel/integracao'
    | '/convite/$token'
    | '/rpc/$'
    | '/rpc/'
    | '/~/'
    | '/_panel/$organizacaoHash/ajustes'
    | '/_panel/$organizacaoHash/contatos'
    | '/_panel/$organizacaoHash/equipe'
    | '/_panel/$organizacaoHash/instancias'
    | '/_panel/$organizacaoHash/integracao'
    | '/_panel/$organizacaoHash/relatorios'
    | '/~/acesso/$token'
    | '/_panel/$organizacaoHash/'
    | '/_panel/$organizacaoHash/ajustes/conexao'
    | '/_panel/$organizacaoHash/ajustes/etiquetas'
    | '/_panel/$organizacaoHash/ajustes/usuarios'
    | '/~/email/$emailHash/bloqueado'
    | '/_panel/$organizacaoHash/ajustes/'
    | '/_panel/$organizacaoHash/inbox/'
    | '/_panel/$organizacaoHash/inbox/$instanceId/'
    | '/_panel/$organizacaoHash/inbox/$instanceId/relatorios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRouteRoute: typeof PanelRouteRouteWithChildren
  ConviteTokenRoute: typeof ConviteTokenRoute
  RpcSplatRoute: typeof RpcSplatRoute
  RpcIndexRoute: typeof RpcIndexRoute
  Char126IndexRoute: typeof Char126IndexRoute
  Char126AcessoTokenRoute: typeof Char126AcessoTokenRoute
  Char126EmailEmailHashBloqueadoRoute: typeof Char126EmailEmailHashBloqueadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~/': {
      id: '/~/'
      path: '/~'
      fullPath: '/~/'
      preLoaderRoute: typeof Char126IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/': {
      id: '/rpc/'
      path: '/rpc'
      fullPath: '/rpc/'
      preLoaderRoute: typeof RpcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/integracao': {
      id: '/_panel/integracao'
      path: '/integracao'
      fullPath: '/integracao'
      preLoaderRoute: typeof PanelIntegracaoRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/_panel/$organizacaoHash': {
      id: '/_panel/$organizacaoHash'
      path: '/$organizacaoHash'
      fullPath: '/$organizacaoHash'
      preLoaderRoute: typeof PanelOrganizacaoHashRouteRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/_panel/$organizacaoHash/': {
      id: '/_panel/$organizacaoHash/'
      path: '/'
      fullPath: '/$organizacaoHash/'
      preLoaderRoute: typeof PanelOrganizacaoHashIndexRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
    '/~/acesso/$token': {
      id: '/~/acesso/$token'
      path: '/~/acesso/$token'
      fullPath: '/~/acesso/$token'
      preLoaderRoute: typeof Char126AcessoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/$organizacaoHash/relatorios': {
      id: '/_panel/$organizacaoHash/relatorios'
      path: '/relatorios'
      fullPath: '/$organizacaoHash/relatorios'
      preLoaderRoute: typeof PanelOrganizacaoHashRelatoriosRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
    '/_panel/$organizacaoHash/integracao': {
      id: '/_panel/$organizacaoHash/integracao'
      path: '/integracao'
      fullPath: '/$organizacaoHash/integracao'
      preLoaderRoute: typeof PanelOrganizacaoHashIntegracaoRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
    '/_panel/$organizacaoHash/instancias': {
      id: '/_panel/$organizacaoHash/instancias'
      path: '/instancias'
      fullPath: '/$organizacaoHash/instancias'
      preLoaderRoute: typeof PanelOrganizacaoHashInstanciasRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
    '/_panel/$organizacaoHash/equipe': {
      id: '/_panel/$organizacaoHash/equipe'
      path: '/equipe'
      fullPath: '/$organizacaoHash/equipe'
      preLoaderRoute: typeof PanelOrganizacaoHashEquipeRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
    '/_panel/$organizacaoHash/contatos': {
      id: '/_panel/$organizacaoHash/contatos'
      path: '/contatos'
      fullPath: '/$organizacaoHash/contatos'
      preLoaderRoute: typeof PanelOrganizacaoHashContatosRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
    '/_panel/$organizacaoHash/ajustes': {
      id: '/_panel/$organizacaoHash/ajustes'
      path: '/ajustes'
      fullPath: '/$organizacaoHash/ajustes'
      preLoaderRoute: typeof PanelOrganizacaoHashAjustesRouteRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
    '/_panel/$organizacaoHash/inbox/': {
      id: '/_panel/$organizacaoHash/inbox/'
      path: '/inbox'
      fullPath: '/$organizacaoHash/inbox/'
      preLoaderRoute: typeof PanelOrganizacaoHashInboxIndexRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
    '/_panel/$organizacaoHash/ajustes/': {
      id: '/_panel/$organizacaoHash/ajustes/'
      path: '/'
      fullPath: '/$organizacaoHash/ajustes/'
      preLoaderRoute: typeof PanelOrganizacaoHashAjustesIndexRouteImport
      parentRoute: typeof PanelOrganizacaoHashAjustesRouteRoute
    }
    '/~/email/$emailHash/bloqueado': {
      id: '/~/email/$emailHash/bloqueado'
      path: '/~/email/$emailHash/bloqueado'
      fullPath: '/~/email/$emailHash/bloqueado'
      preLoaderRoute: typeof Char126EmailEmailHashBloqueadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/$organizacaoHash/ajustes/usuarios': {
      id: '/_panel/$organizacaoHash/ajustes/usuarios'
      path: '/usuarios'
      fullPath: '/$organizacaoHash/ajustes/usuarios'
      preLoaderRoute: typeof PanelOrganizacaoHashAjustesUsuariosRouteImport
      parentRoute: typeof PanelOrganizacaoHashAjustesRouteRoute
    }
    '/_panel/$organizacaoHash/ajustes/etiquetas': {
      id: '/_panel/$organizacaoHash/ajustes/etiquetas'
      path: '/etiquetas'
      fullPath: '/$organizacaoHash/ajustes/etiquetas'
      preLoaderRoute: typeof PanelOrganizacaoHashAjustesEtiquetasRouteImport
      parentRoute: typeof PanelOrganizacaoHashAjustesRouteRoute
    }
    '/_panel/$organizacaoHash/ajustes/conexao': {
      id: '/_panel/$organizacaoHash/ajustes/conexao'
      path: '/conexao'
      fullPath: '/$organizacaoHash/ajustes/conexao'
      preLoaderRoute: typeof PanelOrganizacaoHashAjustesConexaoRouteImport
      parentRoute: typeof PanelOrganizacaoHashAjustesRouteRoute
    }
    '/_panel/$organizacaoHash/inbox/$instanceId/': {
      id: '/_panel/$organizacaoHash/inbox/$instanceId/'
      path: '/inbox/$instanceId'
      fullPath: '/$organizacaoHash/inbox/$instanceId/'
      preLoaderRoute: typeof PanelOrganizacaoHashInboxInstanceIdIndexRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
    '/_panel/$organizacaoHash/inbox/$instanceId/relatorios/': {
      id: '/_panel/$organizacaoHash/inbox/$instanceId/relatorios/'
      path: '/inbox/$instanceId/relatorios'
      fullPath: '/$organizacaoHash/inbox/$instanceId/relatorios/'
      preLoaderRoute: typeof PanelOrganizacaoHashInboxInstanceIdRelatoriosIndexRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
  }
}

interface PanelOrganizacaoHashAjustesRouteRouteChildren {
  PanelOrganizacaoHashAjustesConexaoRoute: typeof PanelOrganizacaoHashAjustesConexaoRoute
  PanelOrganizacaoHashAjustesEtiquetasRoute: typeof PanelOrganizacaoHashAjustesEtiquetasRoute
  PanelOrganizacaoHashAjustesUsuariosRoute: typeof PanelOrganizacaoHashAjustesUsuariosRoute
  PanelOrganizacaoHashAjustesIndexRoute: typeof PanelOrganizacaoHashAjustesIndexRoute
}

const PanelOrganizacaoHashAjustesRouteRouteChildren: PanelOrganizacaoHashAjustesRouteRouteChildren =
  {
    PanelOrganizacaoHashAjustesConexaoRoute:
      PanelOrganizacaoHashAjustesConexaoRoute,
    PanelOrganizacaoHashAjustesEtiquetasRoute:
      PanelOrganizacaoHashAjustesEtiquetasRoute,
    PanelOrganizacaoHashAjustesUsuariosRoute:
      PanelOrganizacaoHashAjustesUsuariosRoute,
    PanelOrganizacaoHashAjustesIndexRoute:
      PanelOrganizacaoHashAjustesIndexRoute,
  }

const PanelOrganizacaoHashAjustesRouteRouteWithChildren =
  PanelOrganizacaoHashAjustesRouteRoute._addFileChildren(
    PanelOrganizacaoHashAjustesRouteRouteChildren,
  )

interface PanelOrganizacaoHashRouteRouteChildren {
  PanelOrganizacaoHashAjustesRouteRoute: typeof PanelOrganizacaoHashAjustesRouteRouteWithChildren
  PanelOrganizacaoHashContatosRoute: typeof PanelOrganizacaoHashContatosRoute
  PanelOrganizacaoHashEquipeRoute: typeof PanelOrganizacaoHashEquipeRoute
  PanelOrganizacaoHashInstanciasRoute: typeof PanelOrganizacaoHashInstanciasRoute
  PanelOrganizacaoHashIntegracaoRoute: typeof PanelOrganizacaoHashIntegracaoRoute
  PanelOrganizacaoHashRelatoriosRoute: typeof PanelOrganizacaoHashRelatoriosRoute
  PanelOrganizacaoHashIndexRoute: typeof PanelOrganizacaoHashIndexRoute
  PanelOrganizacaoHashInboxIndexRoute: typeof PanelOrganizacaoHashInboxIndexRoute
  PanelOrganizacaoHashInboxInstanceIdIndexRoute: typeof PanelOrganizacaoHashInboxInstanceIdIndexRoute
  PanelOrganizacaoHashInboxInstanceIdRelatoriosIndexRoute: typeof PanelOrganizacaoHashInboxInstanceIdRelatoriosIndexRoute
}

const PanelOrganizacaoHashRouteRouteChildren: PanelOrganizacaoHashRouteRouteChildren =
  {
    PanelOrganizacaoHashAjustesRouteRoute:
      PanelOrganizacaoHashAjustesRouteRouteWithChildren,
    PanelOrganizacaoHashContatosRoute: PanelOrganizacaoHashContatosRoute,
    PanelOrganizacaoHashEquipeRoute: PanelOrganizacaoHashEquipeRoute,
    PanelOrganizacaoHashInstanciasRoute: PanelOrganizacaoHashInstanciasRoute,
    PanelOrganizacaoHashIntegracaoRoute: PanelOrganizacaoHashIntegracaoRoute,
    PanelOrganizacaoHashRelatoriosRoute: PanelOrganizacaoHashRelatoriosRoute,
    PanelOrganizacaoHashIndexRoute: PanelOrganizacaoHashIndexRoute,
    PanelOrganizacaoHashInboxIndexRoute: PanelOrganizacaoHashInboxIndexRoute,
    PanelOrganizacaoHashInboxInstanceIdIndexRoute:
      PanelOrganizacaoHashInboxInstanceIdIndexRoute,
    PanelOrganizacaoHashInboxInstanceIdRelatoriosIndexRoute:
      PanelOrganizacaoHashInboxInstanceIdRelatoriosIndexRoute,
  }

const PanelOrganizacaoHashRouteRouteWithChildren =
  PanelOrganizacaoHashRouteRoute._addFileChildren(
    PanelOrganizacaoHashRouteRouteChildren,
  )

interface PanelRouteRouteChildren {
  PanelOrganizacaoHashRouteRoute: typeof PanelOrganizacaoHashRouteRouteWithChildren
  PanelIntegracaoRoute: typeof PanelIntegracaoRoute
}

const PanelRouteRouteChildren: PanelRouteRouteChildren = {
  PanelOrganizacaoHashRouteRoute: PanelOrganizacaoHashRouteRouteWithChildren,
  PanelIntegracaoRoute: PanelIntegracaoRoute,
}

const PanelRouteRouteWithChildren = PanelRouteRoute._addFileChildren(
  PanelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRouteRoute: PanelRouteRouteWithChildren,
  ConviteTokenRoute: ConviteTokenRoute,
  RpcSplatRoute: RpcSplatRoute,
  RpcIndexRoute: RpcIndexRoute,
  Char126IndexRoute: Char126IndexRoute,
  Char126AcessoTokenRoute: Char126AcessoTokenRoute,
  Char126EmailEmailHashBloqueadoRoute: Char126EmailEmailHashBloqueadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
