/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char126RouteRouteImport } from './routes/~.route'
import { Route as PanelRouteRouteImport } from './routes/_panel/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char126IndexRouteImport } from './routes/~.index'
import { Route as RpcIndexRouteImport } from './routes/rpc/index'
import { Route as Char126HashRouteImport } from './routes/~.$hash'
import { Route as RpcSplatRouteImport } from './routes/rpc/$'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as PanelIntegracaoRouteImport } from './routes/_panel/integracao'
import { Route as PanelOrganizacaoHashRouteRouteImport } from './routes/_panel/$organizacaoHash/route'
import { Route as PanelOrganizacaoHashIndexRouteImport } from './routes/_panel/$organizacaoHash/index'
import { Route as PanelOrganizacaoHashRelatoriosRouteImport } from './routes/_panel/$organizacaoHash/relatorios'
import { Route as PanelOrganizacaoHashIntegracaoRouteImport } from './routes/_panel/$organizacaoHash/integracao'
import { Route as PanelOrganizacaoHashInstanciasRouteImport } from './routes/_panel/$organizacaoHash/instancias'
import { Route as PanelOrganizacaoHashEquipeRouteImport } from './routes/_panel/$organizacaoHash/equipe'
import { Route as PanelOrganizacaoHashAjustesRouteImport } from './routes/_panel/$organizacaoHash/ajustes'
import { Route as Char126EmailEmailHashIndexRouteImport } from './routes/~/email/$emailHash/index'
import { Route as Char126EmailEmailHashBloqueadoRouteImport } from './routes/~/email/$emailHash/bloqueado'
import { Route as PanelOrganizacaoHashInboxInstanceIdRouteImport } from './routes/_panel/$organizacaoHash/inbox.$instanceId'

const Char126RouteRoute = Char126RouteRouteImport.update({
  id: '/~',
  path: '/~',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRouteRoute = PanelRouteRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char126IndexRoute = Char126IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char126RouteRoute,
} as any)
const RpcIndexRoute = RpcIndexRouteImport.update({
  id: '/rpc/',
  path: '/rpc/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char126HashRoute = Char126HashRouteImport.update({
  id: '/$hash',
  path: '/$hash',
  getParentRoute: () => Char126RouteRoute,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIntegracaoRoute = PanelIntegracaoRouteImport.update({
  id: '/integracao',
  path: '/integracao',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelOrganizacaoHashRouteRoute =
  PanelOrganizacaoHashRouteRouteImport.update({
    id: '/$organizacaoHash',
    path: '/$organizacaoHash',
    getParentRoute: () => PanelRouteRoute,
  } as any)
const PanelOrganizacaoHashIndexRoute =
  PanelOrganizacaoHashIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)
const PanelOrganizacaoHashRelatoriosRoute =
  PanelOrganizacaoHashRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)
const PanelOrganizacaoHashIntegracaoRoute =
  PanelOrganizacaoHashIntegracaoRouteImport.update({
    id: '/integracao',
    path: '/integracao',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)
const PanelOrganizacaoHashInstanciasRoute =
  PanelOrganizacaoHashInstanciasRouteImport.update({
    id: '/instancias',
    path: '/instancias',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)
const PanelOrganizacaoHashEquipeRoute =
  PanelOrganizacaoHashEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)
const PanelOrganizacaoHashAjustesRoute =
  PanelOrganizacaoHashAjustesRouteImport.update({
    id: '/ajustes',
    path: '/ajustes',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)
const Char126EmailEmailHashIndexRoute =
  Char126EmailEmailHashIndexRouteImport.update({
    id: '/email/$emailHash/',
    path: '/email/$emailHash/',
    getParentRoute: () => Char126RouteRoute,
  } as any)
const Char126EmailEmailHashBloqueadoRoute =
  Char126EmailEmailHashBloqueadoRouteImport.update({
    id: '/email/$emailHash/bloqueado',
    path: '/email/$emailHash/bloqueado',
    getParentRoute: () => Char126RouteRoute,
  } as any)
const PanelOrganizacaoHashInboxInstanceIdRoute =
  PanelOrganizacaoHashInboxInstanceIdRouteImport.update({
    id: '/inbox/$instanceId',
    path: '/inbox/$instanceId',
    getParentRoute: () => PanelOrganizacaoHashRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/~': typeof Char126RouteRouteWithChildren
  '/$organizacaoHash': typeof PanelOrganizacaoHashRouteRouteWithChildren
  '/integracao': typeof PanelIntegracaoRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/rpc/$': typeof RpcSplatRoute
  '/~/$hash': typeof Char126HashRoute
  '/rpc/': typeof RpcIndexRoute
  '/~/': typeof Char126IndexRoute
  '/$organizacaoHash/ajustes': typeof PanelOrganizacaoHashAjustesRoute
  '/$organizacaoHash/equipe': typeof PanelOrganizacaoHashEquipeRoute
  '/$organizacaoHash/instancias': typeof PanelOrganizacaoHashInstanciasRoute
  '/$organizacaoHash/integracao': typeof PanelOrganizacaoHashIntegracaoRoute
  '/$organizacaoHash/relatorios': typeof PanelOrganizacaoHashRelatoriosRoute
  '/$organizacaoHash/': typeof PanelOrganizacaoHashIndexRoute
  '/$organizacaoHash/inbox/$instanceId': typeof PanelOrganizacaoHashInboxInstanceIdRoute
  '/~/email/$emailHash/bloqueado': typeof Char126EmailEmailHashBloqueadoRoute
  '/~/email/$emailHash/': typeof Char126EmailEmailHashIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integracao': typeof PanelIntegracaoRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/rpc/$': typeof RpcSplatRoute
  '/~/$hash': typeof Char126HashRoute
  '/rpc': typeof RpcIndexRoute
  '/~': typeof Char126IndexRoute
  '/$organizacaoHash/ajustes': typeof PanelOrganizacaoHashAjustesRoute
  '/$organizacaoHash/equipe': typeof PanelOrganizacaoHashEquipeRoute
  '/$organizacaoHash/instancias': typeof PanelOrganizacaoHashInstanciasRoute
  '/$organizacaoHash/integracao': typeof PanelOrganizacaoHashIntegracaoRoute
  '/$organizacaoHash/relatorios': typeof PanelOrganizacaoHashRelatoriosRoute
  '/$organizacaoHash': typeof PanelOrganizacaoHashIndexRoute
  '/$organizacaoHash/inbox/$instanceId': typeof PanelOrganizacaoHashInboxInstanceIdRoute
  '/~/email/$emailHash/bloqueado': typeof Char126EmailEmailHashBloqueadoRoute
  '/~/email/$emailHash': typeof Char126EmailEmailHashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_panel': typeof PanelRouteRouteWithChildren
  '/~': typeof Char126RouteRouteWithChildren
  '/_panel/$organizacaoHash': typeof PanelOrganizacaoHashRouteRouteWithChildren
  '/_panel/integracao': typeof PanelIntegracaoRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/rpc/$': typeof RpcSplatRoute
  '/~/$hash': typeof Char126HashRoute
  '/rpc/': typeof RpcIndexRoute
  '/~/': typeof Char126IndexRoute
  '/_panel/$organizacaoHash/ajustes': typeof PanelOrganizacaoHashAjustesRoute
  '/_panel/$organizacaoHash/equipe': typeof PanelOrganizacaoHashEquipeRoute
  '/_panel/$organizacaoHash/instancias': typeof PanelOrganizacaoHashInstanciasRoute
  '/_panel/$organizacaoHash/integracao': typeof PanelOrganizacaoHashIntegracaoRoute
  '/_panel/$organizacaoHash/relatorios': typeof PanelOrganizacaoHashRelatoriosRoute
  '/_panel/$organizacaoHash/': typeof PanelOrganizacaoHashIndexRoute
  '/_panel/$organizacaoHash/inbox/$instanceId': typeof PanelOrganizacaoHashInboxInstanceIdRoute
  '/~/email/$emailHash/bloqueado': typeof Char126EmailEmailHashBloqueadoRoute
  '/~/email/$emailHash/': typeof Char126EmailEmailHashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/~'
    | '/$organizacaoHash'
    | '/integracao'
    | '/convite/$token'
    | '/rpc/$'
    | '/~/$hash'
    | '/rpc/'
    | '/~/'
    | '/$organizacaoHash/ajustes'
    | '/$organizacaoHash/equipe'
    | '/$organizacaoHash/instancias'
    | '/$organizacaoHash/integracao'
    | '/$organizacaoHash/relatorios'
    | '/$organizacaoHash/'
    | '/$organizacaoHash/inbox/$instanceId'
    | '/~/email/$emailHash/bloqueado'
    | '/~/email/$emailHash/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/integracao'
    | '/convite/$token'
    | '/rpc/$'
    | '/~/$hash'
    | '/rpc'
    | '/~'
    | '/$organizacaoHash/ajustes'
    | '/$organizacaoHash/equipe'
    | '/$organizacaoHash/instancias'
    | '/$organizacaoHash/integracao'
    | '/$organizacaoHash/relatorios'
    | '/$organizacaoHash'
    | '/$organizacaoHash/inbox/$instanceId'
    | '/~/email/$emailHash/bloqueado'
    | '/~/email/$emailHash'
  id:
    | '__root__'
    | '/'
    | '/_panel'
    | '/~'
    | '/_panel/$organizacaoHash'
    | '/_panel/integracao'
    | '/convite/$token'
    | '/rpc/$'
    | '/~/$hash'
    | '/rpc/'
    | '/~/'
    | '/_panel/$organizacaoHash/ajustes'
    | '/_panel/$organizacaoHash/equipe'
    | '/_panel/$organizacaoHash/instancias'
    | '/_panel/$organizacaoHash/integracao'
    | '/_panel/$organizacaoHash/relatorios'
    | '/_panel/$organizacaoHash/'
    | '/_panel/$organizacaoHash/inbox/$instanceId'
    | '/~/email/$emailHash/bloqueado'
    | '/~/email/$emailHash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRouteRoute: typeof PanelRouteRouteWithChildren
  Char126RouteRoute: typeof Char126RouteRouteWithChildren
  ConviteTokenRoute: typeof ConviteTokenRoute
  RpcSplatRoute: typeof RpcSplatRoute
  RpcIndexRoute: typeof RpcIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/~': {
      id: '/~'
      path: '/~'
      fullPath: '/~'
      preLoaderRoute: typeof Char126RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~/': {
      id: '/~/'
      path: '/'
      fullPath: '/~/'
      preLoaderRoute: typeof Char126IndexRouteImport
      parentRoute: typeof Char126RouteRoute
    }
    '/rpc/': {
      id: '/rpc/'
      path: '/rpc'
      fullPath: '/rpc/'
      preLoaderRoute: typeof RpcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~/$hash': {
      id: '/~/$hash'
      path: '/$hash'
      fullPath: '/~/$hash'
      preLoaderRoute: typeof Char126HashRouteImport
      parentRoute: typeof Char126RouteRoute
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/integracao': {
      id: '/_panel/integracao'
      path: '/integracao'
      fullPath: '/integracao'
      preLoaderRoute: typeof PanelIntegracaoRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/_panel/$organizacaoHash': {
      id: '/_panel/$organizacaoHash'
      path: '/$organizacaoHash'
      fullPath: '/$organizacaoHash'
      preLoaderRoute: typeof PanelOrganizacaoHashRouteRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/_panel/$organizacaoHash/': {
      id: '/_panel/$organizacaoHash/'
      path: '/'
      fullPath: '/$organizacaoHash/'
      preLoaderRoute: typeof PanelOrganizacaoHashIndexRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
    '/_panel/$organizacaoHash/relatorios': {
      id: '/_panel/$organizacaoHash/relatorios'
      path: '/relatorios'
      fullPath: '/$organizacaoHash/relatorios'
      preLoaderRoute: typeof PanelOrganizacaoHashRelatoriosRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
    '/_panel/$organizacaoHash/integracao': {
      id: '/_panel/$organizacaoHash/integracao'
      path: '/integracao'
      fullPath: '/$organizacaoHash/integracao'
      preLoaderRoute: typeof PanelOrganizacaoHashIntegracaoRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
    '/_panel/$organizacaoHash/instancias': {
      id: '/_panel/$organizacaoHash/instancias'
      path: '/instancias'
      fullPath: '/$organizacaoHash/instancias'
      preLoaderRoute: typeof PanelOrganizacaoHashInstanciasRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
    '/_panel/$organizacaoHash/equipe': {
      id: '/_panel/$organizacaoHash/equipe'
      path: '/equipe'
      fullPath: '/$organizacaoHash/equipe'
      preLoaderRoute: typeof PanelOrganizacaoHashEquipeRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
    '/_panel/$organizacaoHash/ajustes': {
      id: '/_panel/$organizacaoHash/ajustes'
      path: '/ajustes'
      fullPath: '/$organizacaoHash/ajustes'
      preLoaderRoute: typeof PanelOrganizacaoHashAjustesRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
    '/~/email/$emailHash/': {
      id: '/~/email/$emailHash/'
      path: '/email/$emailHash'
      fullPath: '/~/email/$emailHash/'
      preLoaderRoute: typeof Char126EmailEmailHashIndexRouteImport
      parentRoute: typeof Char126RouteRoute
    }
    '/~/email/$emailHash/bloqueado': {
      id: '/~/email/$emailHash/bloqueado'
      path: '/email/$emailHash/bloqueado'
      fullPath: '/~/email/$emailHash/bloqueado'
      preLoaderRoute: typeof Char126EmailEmailHashBloqueadoRouteImport
      parentRoute: typeof Char126RouteRoute
    }
    '/_panel/$organizacaoHash/inbox/$instanceId': {
      id: '/_panel/$organizacaoHash/inbox/$instanceId'
      path: '/inbox/$instanceId'
      fullPath: '/$organizacaoHash/inbox/$instanceId'
      preLoaderRoute: typeof PanelOrganizacaoHashInboxInstanceIdRouteImport
      parentRoute: typeof PanelOrganizacaoHashRouteRoute
    }
  }
}

interface PanelOrganizacaoHashRouteRouteChildren {
  PanelOrganizacaoHashAjustesRoute: typeof PanelOrganizacaoHashAjustesRoute
  PanelOrganizacaoHashEquipeRoute: typeof PanelOrganizacaoHashEquipeRoute
  PanelOrganizacaoHashInstanciasRoute: typeof PanelOrganizacaoHashInstanciasRoute
  PanelOrganizacaoHashIntegracaoRoute: typeof PanelOrganizacaoHashIntegracaoRoute
  PanelOrganizacaoHashRelatoriosRoute: typeof PanelOrganizacaoHashRelatoriosRoute
  PanelOrganizacaoHashIndexRoute: typeof PanelOrganizacaoHashIndexRoute
  PanelOrganizacaoHashInboxInstanceIdRoute: typeof PanelOrganizacaoHashInboxInstanceIdRoute
}

const PanelOrganizacaoHashRouteRouteChildren: PanelOrganizacaoHashRouteRouteChildren =
  {
    PanelOrganizacaoHashAjustesRoute: PanelOrganizacaoHashAjustesRoute,
    PanelOrganizacaoHashEquipeRoute: PanelOrganizacaoHashEquipeRoute,
    PanelOrganizacaoHashInstanciasRoute: PanelOrganizacaoHashInstanciasRoute,
    PanelOrganizacaoHashIntegracaoRoute: PanelOrganizacaoHashIntegracaoRoute,
    PanelOrganizacaoHashRelatoriosRoute: PanelOrganizacaoHashRelatoriosRoute,
    PanelOrganizacaoHashIndexRoute: PanelOrganizacaoHashIndexRoute,
    PanelOrganizacaoHashInboxInstanceIdRoute:
      PanelOrganizacaoHashInboxInstanceIdRoute,
  }

const PanelOrganizacaoHashRouteRouteWithChildren =
  PanelOrganizacaoHashRouteRoute._addFileChildren(
    PanelOrganizacaoHashRouteRouteChildren,
  )

interface PanelRouteRouteChildren {
  PanelOrganizacaoHashRouteRoute: typeof PanelOrganizacaoHashRouteRouteWithChildren
  PanelIntegracaoRoute: typeof PanelIntegracaoRoute
}

const PanelRouteRouteChildren: PanelRouteRouteChildren = {
  PanelOrganizacaoHashRouteRoute: PanelOrganizacaoHashRouteRouteWithChildren,
  PanelIntegracaoRoute: PanelIntegracaoRoute,
}

const PanelRouteRouteWithChildren = PanelRouteRoute._addFileChildren(
  PanelRouteRouteChildren,
)

interface Char126RouteRouteChildren {
  Char126HashRoute: typeof Char126HashRoute
  Char126IndexRoute: typeof Char126IndexRoute
  Char126EmailEmailHashBloqueadoRoute: typeof Char126EmailEmailHashBloqueadoRoute
  Char126EmailEmailHashIndexRoute: typeof Char126EmailEmailHashIndexRoute
}

const Char126RouteRouteChildren: Char126RouteRouteChildren = {
  Char126HashRoute: Char126HashRoute,
  Char126IndexRoute: Char126IndexRoute,
  Char126EmailEmailHashBloqueadoRoute: Char126EmailEmailHashBloqueadoRoute,
  Char126EmailEmailHashIndexRoute: Char126EmailEmailHashIndexRoute,
}

const Char126RouteRouteWithChildren = Char126RouteRoute._addFileChildren(
  Char126RouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRouteRoute: PanelRouteRouteWithChildren,
  Char126RouteRoute: Char126RouteRouteWithChildren,
  ConviteTokenRoute: ConviteTokenRoute,
  RpcSplatRoute: RpcSplatRoute,
  RpcIndexRoute: RpcIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
