/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteRouteImport } from './routes/_panel/route'
import { Route as RpcIndexRouteImport } from './routes/rpc/index'
import { Route as PanelIndexRouteImport } from './routes/_panel/index'
import { Route as RpcSplatRouteImport } from './routes/rpc/$'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as PanelRelatoriosRouteImport } from './routes/_panel/relatorios'
import { Route as PanelOnboardingRouteImport } from './routes/_panel/onboarding'
import { Route as PanelInstanciasRouteImport } from './routes/_panel/instancias'
import { Route as PanelEquipeRouteImport } from './routes/_panel/equipe'
import { Route as PanelAjustesRouteImport } from './routes/_panel/ajustes'
import { Route as PanelInboxInstanceIdRouteImport } from './routes/_panel/inbox.$instanceId'

const PanelRouteRoute = PanelRouteRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcIndexRoute = RpcIndexRouteImport.update({
  id: '/rpc/',
  path: '/rpc/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRelatoriosRoute = PanelRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelOnboardingRoute = PanelOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelInstanciasRoute = PanelInstanciasRouteImport.update({
  id: '/instancias',
  path: '/instancias',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelEquipeRoute = PanelEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelAjustesRoute = PanelAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelInboxInstanceIdRoute = PanelInboxInstanceIdRouteImport.update({
  id: '/inbox/$instanceId',
  path: '/inbox/$instanceId',
  getParentRoute: () => PanelRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PanelIndexRoute
  '/ajustes': typeof PanelAjustesRoute
  '/equipe': typeof PanelEquipeRoute
  '/instancias': typeof PanelInstanciasRoute
  '/onboarding': typeof PanelOnboardingRoute
  '/relatorios': typeof PanelRelatoriosRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/rpc/$': typeof RpcSplatRoute
  '/rpc/': typeof RpcIndexRoute
  '/inbox/$instanceId': typeof PanelInboxInstanceIdRoute
}
export interface FileRoutesByTo {
  '/ajustes': typeof PanelAjustesRoute
  '/equipe': typeof PanelEquipeRoute
  '/instancias': typeof PanelInstanciasRoute
  '/onboarding': typeof PanelOnboardingRoute
  '/relatorios': typeof PanelRelatoriosRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/rpc/$': typeof RpcSplatRoute
  '/': typeof PanelIndexRoute
  '/rpc': typeof RpcIndexRoute
  '/inbox/$instanceId': typeof PanelInboxInstanceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_panel': typeof PanelRouteRouteWithChildren
  '/_panel/ajustes': typeof PanelAjustesRoute
  '/_panel/equipe': typeof PanelEquipeRoute
  '/_panel/instancias': typeof PanelInstanciasRoute
  '/_panel/onboarding': typeof PanelOnboardingRoute
  '/_panel/relatorios': typeof PanelRelatoriosRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/rpc/$': typeof RpcSplatRoute
  '/_panel/': typeof PanelIndexRoute
  '/rpc/': typeof RpcIndexRoute
  '/_panel/inbox/$instanceId': typeof PanelInboxInstanceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/equipe'
    | '/instancias'
    | '/onboarding'
    | '/relatorios'
    | '/convite/$token'
    | '/rpc/$'
    | '/rpc/'
    | '/inbox/$instanceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ajustes'
    | '/equipe'
    | '/instancias'
    | '/onboarding'
    | '/relatorios'
    | '/convite/$token'
    | '/rpc/$'
    | '/'
    | '/rpc'
    | '/inbox/$instanceId'
  id:
    | '__root__'
    | '/_panel'
    | '/_panel/ajustes'
    | '/_panel/equipe'
    | '/_panel/instancias'
    | '/_panel/onboarding'
    | '/_panel/relatorios'
    | '/convite/$token'
    | '/rpc/$'
    | '/_panel/'
    | '/rpc/'
    | '/_panel/inbox/$instanceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PanelRouteRoute: typeof PanelRouteRouteWithChildren
  ConviteTokenRoute: typeof ConviteTokenRoute
  RpcSplatRoute: typeof RpcSplatRoute
  RpcIndexRoute: typeof RpcIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/': {
      id: '/rpc/'
      path: '/rpc'
      fullPath: '/rpc/'
      preLoaderRoute: typeof RpcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/': {
      id: '/_panel/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/relatorios': {
      id: '/_panel/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof PanelRelatoriosRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/_panel/onboarding': {
      id: '/_panel/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof PanelOnboardingRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/_panel/instancias': {
      id: '/_panel/instancias'
      path: '/instancias'
      fullPath: '/instancias'
      preLoaderRoute: typeof PanelInstanciasRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/_panel/equipe': {
      id: '/_panel/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof PanelEquipeRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/_panel/ajustes': {
      id: '/_panel/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof PanelAjustesRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/_panel/inbox/$instanceId': {
      id: '/_panel/inbox/$instanceId'
      path: '/inbox/$instanceId'
      fullPath: '/inbox/$instanceId'
      preLoaderRoute: typeof PanelInboxInstanceIdRouteImport
      parentRoute: typeof PanelRouteRoute
    }
  }
}

interface PanelRouteRouteChildren {
  PanelAjustesRoute: typeof PanelAjustesRoute
  PanelEquipeRoute: typeof PanelEquipeRoute
  PanelInstanciasRoute: typeof PanelInstanciasRoute
  PanelOnboardingRoute: typeof PanelOnboardingRoute
  PanelRelatoriosRoute: typeof PanelRelatoriosRoute
  PanelIndexRoute: typeof PanelIndexRoute
  PanelInboxInstanceIdRoute: typeof PanelInboxInstanceIdRoute
}

const PanelRouteRouteChildren: PanelRouteRouteChildren = {
  PanelAjustesRoute: PanelAjustesRoute,
  PanelEquipeRoute: PanelEquipeRoute,
  PanelInstanciasRoute: PanelInstanciasRoute,
  PanelOnboardingRoute: PanelOnboardingRoute,
  PanelRelatoriosRoute: PanelRelatoriosRoute,
  PanelIndexRoute: PanelIndexRoute,
  PanelInboxInstanceIdRoute: PanelInboxInstanceIdRoute,
}

const PanelRouteRouteWithChildren = PanelRouteRoute._addFileChildren(
  PanelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PanelRouteRoute: PanelRouteRouteWithChildren,
  ConviteTokenRoute: ConviteTokenRoute,
  RpcSplatRoute: RpcSplatRoute,
  RpcIndexRoute: RpcIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
