/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as IndiqueRouteImport } from './routes/indique'
import { Route as EnvioEmMassaRouteImport } from './routes/envio-em-massa'
import { Route as ContadoresRouteImport } from './routes/contadores'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Webinars02072026RouteImport } from './routes/webinars/02-07-2026'
import { Route as ApiOrcamentoRouteImport } from './routes/api/orcamento'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiqueRoute = IndiqueRouteImport.update({
  id: '/indique',
  path: '/indique',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvioEmMassaRoute = EnvioEmMassaRouteImport.update({
  id: '/envio-em-massa',
  path: '/envio-em-massa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContadoresRoute = ContadoresRouteImport.update({
  id: '/contadores',
  path: '/contadores',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Webinars02072026Route = Webinars02072026RouteImport.update({
  id: '/webinars/02-07-2026',
  path: '/webinars/02-07-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrcamentoRoute = ApiOrcamentoRouteImport.update({
  id: '/api/orcamento',
  path: '/api/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/contadores': typeof ContadoresRoute
  '/envio-em-massa': typeof EnvioEmMassaRoute
  '/indique': typeof IndiqueRoute
  '/legal': typeof LegalRoute
  '/precos': typeof PrecosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/orcamento': typeof ApiOrcamentoRoute
  '/webinars/02-07-2026': typeof Webinars02072026Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/contadores': typeof ContadoresRoute
  '/envio-em-massa': typeof EnvioEmMassaRoute
  '/indique': typeof IndiqueRoute
  '/legal': typeof LegalRoute
  '/precos': typeof PrecosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/orcamento': typeof ApiOrcamentoRoute
  '/webinars/02-07-2026': typeof Webinars02072026Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/contadores': typeof ContadoresRoute
  '/envio-em-massa': typeof EnvioEmMassaRoute
  '/indique': typeof IndiqueRoute
  '/legal': typeof LegalRoute
  '/precos': typeof PrecosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/orcamento': typeof ApiOrcamentoRoute
  '/webinars/02-07-2026': typeof Webinars02072026Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculadora'
    | '/contadores'
    | '/envio-em-massa'
    | '/indique'
    | '/legal'
    | '/precos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/orcamento'
    | '/webinars/02-07-2026'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculadora'
    | '/contadores'
    | '/envio-em-massa'
    | '/indique'
    | '/legal'
    | '/precos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/orcamento'
    | '/webinars/02-07-2026'
  id:
    | '__root__'
    | '/'
    | '/calculadora'
    | '/contadores'
    | '/envio-em-massa'
    | '/indique'
    | '/legal'
    | '/precos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/orcamento'
    | '/webinars/02-07-2026'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculadoraRoute: typeof CalculadoraRoute
  ContadoresRoute: typeof ContadoresRoute
  EnvioEmMassaRoute: typeof EnvioEmMassaRoute
  IndiqueRoute: typeof IndiqueRoute
  LegalRoute: typeof LegalRoute
  PrecosRoute: typeof PrecosRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiOrcamentoRoute: typeof ApiOrcamentoRoute
  Webinars02072026Route: typeof Webinars02072026Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indique': {
      id: '/indique'
      path: '/indique'
      fullPath: '/indique'
      preLoaderRoute: typeof IndiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envio-em-massa': {
      id: '/envio-em-massa'
      path: '/envio-em-massa'
      fullPath: '/envio-em-massa'
      preLoaderRoute: typeof EnvioEmMassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contadores': {
      id: '/contadores'
      path: '/contadores'
      fullPath: '/contadores'
      preLoaderRoute: typeof ContadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webinars/02-07-2026': {
      id: '/webinars/02-07-2026'
      path: '/webinars/02-07-2026'
      fullPath: '/webinars/02-07-2026'
      preLoaderRoute: typeof Webinars02072026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orcamento': {
      id: '/api/orcamento'
      path: '/api/orcamento'
      fullPath: '/api/orcamento'
      preLoaderRoute: typeof ApiOrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculadoraRoute: CalculadoraRoute,
  ContadoresRoute: ContadoresRoute,
  EnvioEmMassaRoute: EnvioEmMassaRoute,
  IndiqueRoute: IndiqueRoute,
  LegalRoute: LegalRoute,
  PrecosRoute: PrecosRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiOrcamentoRoute: ApiOrcamentoRoute,
  Webinars02072026Route: Webinars02072026Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
