/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as IndiqueRouteImport } from './routes/indique'
import { Route as EnvioEmMassaRouteImport } from './routes/envio-em-massa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOrcamentoRouteImport } from './routes/api/orcamento'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiqueRoute = IndiqueRouteImport.update({
  id: '/indique',
  path: '/indique',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvioEmMassaRoute = EnvioEmMassaRouteImport.update({
  id: '/envio-em-massa',
  path: '/envio-em-massa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrcamentoRoute = ApiOrcamentoRouteImport.update({
  id: '/api/orcamento',
  path: '/api/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/envio-em-massa': typeof EnvioEmMassaRoute
  '/indique': typeof IndiqueRoute
  '/legal': typeof LegalRoute
  '/precos': typeof PrecosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/orcamento': typeof ApiOrcamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/envio-em-massa': typeof EnvioEmMassaRoute
  '/indique': typeof IndiqueRoute
  '/legal': typeof LegalRoute
  '/precos': typeof PrecosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/orcamento': typeof ApiOrcamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/envio-em-massa': typeof EnvioEmMassaRoute
  '/indique': typeof IndiqueRoute
  '/legal': typeof LegalRoute
  '/precos': typeof PrecosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/orcamento': typeof ApiOrcamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/envio-em-massa'
    | '/indique'
    | '/legal'
    | '/precos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/orcamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/envio-em-massa'
    | '/indique'
    | '/legal'
    | '/precos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/orcamento'
  id:
    | '__root__'
    | '/'
    | '/envio-em-massa'
    | '/indique'
    | '/legal'
    | '/precos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/orcamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnvioEmMassaRoute: typeof EnvioEmMassaRoute
  IndiqueRoute: typeof IndiqueRoute
  LegalRoute: typeof LegalRoute
  PrecosRoute: typeof PrecosRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiOrcamentoRoute: typeof ApiOrcamentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indique': {
      id: '/indique'
      path: '/indique'
      fullPath: '/indique'
      preLoaderRoute: typeof IndiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envio-em-massa': {
      id: '/envio-em-massa'
      path: '/envio-em-massa'
      fullPath: '/envio-em-massa'
      preLoaderRoute: typeof EnvioEmMassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orcamento': {
      id: '/api/orcamento'
      path: '/api/orcamento'
      fullPath: '/api/orcamento'
      preLoaderRoute: typeof ApiOrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnvioEmMassaRoute: EnvioEmMassaRoute,
  IndiqueRoute: IndiqueRoute,
  LegalRoute: LegalRoute,
  PrecosRoute: PrecosRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiOrcamentoRoute: ApiOrcamentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
