/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RpcIndexRouteImport } from './routes/rpc/index'
import { Route as RpcSplatRouteImport } from './routes/rpc/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcIndexRoute = RpcIndexRouteImport.update({
  id: '/rpc/',
  path: '/rpc/',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rpc/$': typeof RpcSplatRoute
  '/rpc/': typeof RpcIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rpc/$': typeof RpcSplatRoute
  '/rpc': typeof RpcIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rpc/$': typeof RpcSplatRoute
  '/rpc/': typeof RpcIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rpc/$' | '/rpc/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rpc/$' | '/rpc'
  id: '__root__' | '/' | '/rpc/$' | '/rpc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RpcSplatRoute: typeof RpcSplatRoute
  RpcIndexRoute: typeof RpcIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/': {
      id: '/rpc/'
      path: '/rpc'
      fullPath: '/rpc/'
      preLoaderRoute: typeof RpcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RpcSplatRoute: RpcSplatRoute,
  RpcIndexRoute: RpcIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
